spring.application.name=forum

# Datasource (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/forum_database
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# H2 console desativado (não precisamos mais)
spring.h2.console.enabled=false

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.url=/openapi.yaml
springdoc.swagger-ui.disable-swagger-default-url=true
